### ISSUE TITLE
itemize list style is not appropriate

### ISSUE THREAD

**Issue by cabbage63** [satopirka/md2mail#1]
When writing itemize list notation in markdown like below
```
- a
  - b
  - c
- d
  - e
```

preview shows;
```
・abc
・de
```

following output should be appropriate
```
・a
　・b
　・c
・d
　・e
```

**Comment by minatosato** [comment]
I fixed this issue! with a commit d34d87ecf241e807d683590115e9c92ab0554090.
Enjoy!
